---
title: "Сетевой анализ дискурса постгуманистической философии"
author: "Нискин Е. А."
date: 2026-06-19
format:
  html:
    toc: true
    theme: flatly
    lang: ru
---

### О проекте
В этом исследовании Digital Humanities мне бы хотелось изучить поле мыслителей, в той или иной степени относимых к одному из самых актуальных философских направлений конца XX - начала XXI вв. — *постгуманизму*. Любое научное дискурсивное поле состоит из авторов (тех, кто в нём говорит), а также их способов говорить (в данном случае речь о книгах, статьях и прочих видах текстов), и история философии работает с множеством таких дискурсивных полей: к примеру, поле неоплатоников, поле немецких идеалистов, поле русских христианских философов и т.д. Однако проблема состоит в том, что мы не всегда способны подняться на "уровень птичьего полёта" и посмотреть, кто на кого ссылается в дискурсе, кто кого цитирует, в каких книгах и т.д. просто из-за того, что информации очень много. Поэтому для любого историка философии хорошим инструментом в работе является **визуализация**, с помощью которой он может видеть всю сеть целиком и делать выводы о влиятельности того или иного исследователя в его поле по соответствующим метрикам. Это исследование предлагает провести ту же самую задачу в поле постгуманистической философии — визуализировать постгуманистический дискурс при помощи сетевого анализа. Результаты могут очень пригодиться философам, историкам современной философии и всем, кто хочет ознакомиться с постгуманизмом.

* ### Цель работы
Методом сетевого анализа составить систему цитирований в постгуманистической философии и определить, кто является ключевыми авторами в постгуманизме.

* ### Задачи работы
1) Составить датасет авторов, занимавшихся постгуманистической философией или связанных с ней. В подготовке датасета я опирался на обзорные книги Дмитрия Хаустова *"Тёмные теории"* (2026) и Кэри Вулф *"What is Posthumanism?"* (2010), а также статью о постгуманизме в Википедии (https://en.wikipedia.org/wiki/Posthumanism). Собрано 23 автора и 44 книги.
2) При помощи регулярных выражений, библиотеки `pymupdf` и модуля `fitz` найти библиографические разделы в книгах и вычленить оттуда цитирования, которые потом станут рёбрами в графе.
3) Из собранной таблицы с данными сформировать граф и сделать общие выводы.

* ### Выбор датасета
Опираясь на вышеуказанные источники, особенно на *"Тёмные теории"* Д. Хаустова, я постарался собрать наиболее важных авторов для постгуманизма, а у них — самые цитируемые работы. Разумеется, список не исчерпаем и может быть дополнен другими философами и менее цитируемыми текстами, однако у нашего исследования есть технический предел. Кроме того, в списке философов присутствуют те, которые не являются постгуманистами в строгом смысле, но которые оказали наибольшее влияние на это направление: постструктуралист Жиль Делёз, философы техники Бернар Стиглер и Жильбер Симондон и всем известный экзистенциалист Мартин Хайдеггер. Без этих мыслителей картина постгуманистического дискурса была бы неполной и разреженной.

::: {.callout-note}
## Применимость к другим исследованиям
При имеющимся датасете этот код теоретически может быть применим к **любому дискурсивному полю** с учётом нескольких условий:  
1) каждый PDF-файл из датасета имеет распознаваемый текст;  
2) в каждой книге есть библиографический раздел;  
3) каждый автор хотя бы раз либо цитировал кого-то из других авторов в датасете, либо был процитирован ими (иначе автор выпадет из сети).
:::

## Шаг 1. Импорт библиотек

`pymupdf` — основная библиотека PyMuPDF для работы с PDF-файлами  
`os` — путь к файлам  
`re` — регулярные выражения  
`pandas` as `pd` — табличные данные  
`networkx` as `nx` — графы  
`from pyvis.network import Network` — визуализация графов в HTML  
`matplotlib.pyplot` as `plt` — визуализация  

## Шаг 2. Составление словаря авторов

Переменная `folder` хранит название папки с датасетом, а `AUTHORS` — словарь с именами и фамилиями философов. Ключ - фамилия по-английски, значение - имя на русском.

```python
folder = "project_posthumanism"

AUTHORS = {
    "latour": "Б. Латур",
    "stiegler": "Б. Стиглер",
    "colebrook": "К. Колбрук",
    "wolfe": "К. Вулф",
    "haraway": "Д. Харауэй",
    "thacker": "Ю. Такер",
    "ferrando": "Ф. Феррандо",
    "deleuze": "Ж. Делёз",
    "harman": "Г. Харман",
    "simondon": "Ж. Симондон",
    "grant": "И.Г. Грант",
    "bennett": "Дж. Беннетт",
    "barad": "К. Барад",
    "delanda": "М. ДеЛанда",
    "heidegger": "М. Хайдеггер",
    "hayles": "Н. Кэтрин Хейлс",
    "land": "Н. Ланд",
    "meillassoux": "К. Мейясу",
    "braidotti": "Р. Брайдотти",
    "brassier": "Р. Брассье",
    "negarestani": "Р. Негарестани",
    "ligotti": "Т. Лиготти",
    "morton": "Т. Мортон",
}
```

## Шаг 3. Парсинг имени файла

В этой ячейке мы создаём функцию, которая будет парсить имя файла и возвращать фамилию автора на английском языке. Это нужно для того, чтобы в дальнейшем сопоставлять имена авторов с их цитированием в библиографических разделах.

## Шаг 4. Функции для поиска цитирований

1) `def extract_text(path)` — извлекает текст из PDF-файла и склеивает его в одну строку
2) `def find_bibliography(text)` — находит начало раздела библиографии и возвращаем текст от него до конца вместе с заголовком. Если ни того, ни другого нет — `None`.
3) `def find_quotes(text)` — собирает всех авторов из словаря `AUTHORS` в библиографическом разделе и отдельно рассматривает фамилии Grant и Land

**Важная оговорка.** В этом проекте нет задачи рассматривать каждый текст вне библиографических разделов. На то есть две причины. Во-первых, существуют технические пределы и составить код, позволивший бы искать сноски, примечания и прочие дополнения любого текста, — достаточно непростая задача. Во-вторых, нам неважно, сколько раз один автор процитировал другого во всём тексте. Нужен сам факт влияния, который подтверждается хотя бы одним упоминанием имени в библиографии. Поэтому нас не интересует анализ точного количества цитирований одного автора другим, что требует, как я уже сказал, гораздо более сложного кода. Тем не менее я оцениваю уровень влияния по количеству книг (к примеру, если Харауэй упоминала Делёза в 2-х книгах, то вес ребра между ними будет больше — об этом подробнее в шаге 7).

## Шаг 5. Обработка файлов

На этой ячейке происходит обработка всех файлов из датасета. В результате мы получаем таблицу, в которой указаны все цитирования авторов друг другом.

**Результаты:**

```python
Рёбер: 174  
Файлов без библиографии: 6  
Не удалось обработать: 0  
```

|    | Автор      | Название                | Год  | Кого цитировал | Название раздела |
|----|------------|-------------------------|------|----------------|------------------|
| 0  | Б. Латур   | Laboratory Life         | 1987 | Д. Харауэй     | references       |
| 1  | Б. Латур   | Laboratory Life         | 1987 | М. Хайдеггер   | references       |
| 2  | Б. Латур   | Reassembling the Social | 2005 | Д. Харауэй     | bibliography     |
| 3  | Б. Латур   | Reassembling the Social | 2005 | Ж. Делёз       | bibliography     |
| 4  | Б. Латур   | Science in Action       | 1987 | К. Вулф        | references       |
| 5  | Б. Латур   | We Have Never Been Modern | 1991 | Д. Харауэй   | bibliography     |
| 6  | Б. Латур   | We Have Never Been Modern | 1991 | М. Хайдеггер | bibliography     |
| 7  | Б. Латур   | We Have Never Been Modern | 1991 | Ж. Делёз     | bibliography     |
| 8  | Б. Стиглер | Technics and Time, 1    | 1994 | М. Хайдеггер   | bibliography     |
| 9  | Б. Стиглер | Technics and Time, 1    | 1994 | Ж. Симондон    | bibliography     |
| 10 | Б. Стиглер | Technics and Time, 2    | 1996 | М. Хайдеггер   | notes            |
| 11 | Б. Стиглер | Technics and Time, 2    | 1996 | Ж. Симондон    | notes            |
| 12 | Б. Стиглер | Technics and Time, 2    | 1996 | Ж. Делёз       | notes            |
| 13 | К. Колбрук | Death of the PostHuman  | 2014 | Р. Брайдотти   | works cited      |
| 14 | К. Колбрук | Death of the PostHuman  | 2014 | К. Вулф        | works cited      |

## Шаг 6. Проверка наличия текстов без библиографических разделов

К сожалению, с этими текстами ничего не сделаешь, потому что в них отсутствует библиография. Но мы по-прежнему оставим их в датасете, потому что имена авторов всё равно нужны для поиска по библиографиям.

**Результаты:**

```python
В этих файлах не найден заголовок библиографии:  
- D. Haraway - A Cyborg Manifesto (1985).pdf  
- G. Simondon - On the Mode of Existence of Technical Objects (1958).pdf  
- M. Heidegger - The Question Concerning Technology, and Other Essays (1954).pdf  
- N. Katherine Hayles - How We Became Posthuman (1999).pdf  
- N. Katherine Hayles - Writing Machines (2002).pdf  
- R. Braidotti - Nomadic Subjects (1994).pdf  

Добавьте новые заголовки в BIB_HEADERS.
```

## Шаг 7. Построение графа

Мы строим направленный граф, в котором ребро-стрелка будет идти от одного автора к другому автору, которого первый процитировал. Кроме того, мы придадим каждому ребру вес в зависимости от количества книг, в которых есть пара цитирующего и цитируемого.

## Шаг 8. Вывод самых влиятельных авторов из списка

Наиболее влиятельных авторов для постгуманизма мы будем оценивать не по входящим рёбрам, а по известному алгоритму PageRank, изначально задуманному создателями Google. Если не вдаваться в формулу алгоритма, его суть в том, что узел важен, если на него ссылается много других важных узлов. Переводя на язык нашего исследования — цитирование от авторитетной, часто цитируемой, работы весит больше, чем от малозаметной, редко цитируемой.

**Результаты:**

|                 | Кол-во цитирований | Влияние  |
|-----------------|--------------------|----------|
| М. Хайдеггер    | 28                 | 0.180364 |
| Ж. Делёз        | 30                 | 0.136769 |
| Ж. Симондон     | 8                  | 0.094402 |
| Д. Харауэй      | 16                 | 0.063696 |
| Б. Латур        | 16                 | 0.058097 |
| К. Вулф         | 7                  | 0.041734 |
| К. Мейясу       | 8                  | 0.034935 |
| Дж. Беннетт     | 8                  | 0.034713 |
| Н. Кэтрин Хейлс | 7                  | 0.034585 |
| Р. Брассье      | 7                  | 0.031191 |

## Шаг 9. Визуализация

Создаём граф на чёрном фоне с разноцветными узлами, белыми стрелками и именами философов на русском, написанными на чёрном фоне, чтобы они были читабельными.

**Результаты:**

<iframe src="posthumanism_graph.html" width="100%" height="800" frameborder="0"></iframe>

## Шаг 10. Выводы

Сделаем несколько выводов о получившемся графе.

1) Мы видим двух ключевых фигур, которых цитируют чуть ли не все, а они никого не цитируют, поскольку жили раньше остальных исследователей - это Жиль Делёз и Мартин Хайдеггер, что довольно неудивительно, поскольку именно они являются самыми важными для всего постгуманизма. Заметно также, что третьим по величине философом по PageRank является Жильбер Симондон (0.09), не самый большой по in-degree на графе.
2) Следом за Делёзом и Хайдеггером по величине узлов идут Бруно Латур и Донна Харауэй, одни из основателей постгуманистической теории. Как показывают веса рёбер-стрелок, они часто цитируют друг друга и их часто цитируют другие.
3) Наконец, по всему графу можно увидеть множество узлов меньше, это современные постгуманисты, последователи всех вышеназванных 4-х философов. Среди них есть 4 основателя спекулятивного реализма (К. Мейясу, Г. Харман, И. Грант и Р. Брассье), "тёмный эколог" Тимоти Мортон и др. Отдельно стоит указать такое связующее звено всего графа, Ф. Феррандо, исследовательницу постгуманизма, которая процитировала огромное число людей в списке, хотя при этом её не процитировал никто.

## Ограничения и перспективы

Во-первых, **узкий датасет**. Если бы нашей целью стояло исследование абсолютно всего направления постгуманистической философии, то стоило бы брать больше книг у каждого автора, а в лучшем случае — и больше книг, и больше авторов. Граф в этом исследовании указывает на общие характеристики интеллектуального поля постгуманизма, но они не так многогранны, как могли бы быть. 

Во-вторых, **проблема оценки влияния**. Как мы уже указывали ранее, нашей задачей было подтвердить факт влияния, а не его точный уровень. Для точной интерпретации авторитетности исследователей и влияния одного на другого, разумеется, имеет смысл написать код, который мог бы анализировать всё содержание каждой книги: точные цитаты в тексте, сноски, примечания, методологию и прочие дополнения, где могли бы быть указаны дополнительные авторы. 

В-третьих, как продолжение второго ограничения, **отсутствие библиографий**. А что делать, если библиографий нет вовсе? Тут данный проект приходит в тупик, потому что работает только с библиографическими разделами. Поэтому, к сожалению, погрешность оказалось неизбежной и, как выяснилось, в 6 текстах из датасета отсутствовала библиография или доп. примечания.

::: {.callout-note}
## Итог
Итак, можно заключить, что **это исследование вполне доступно для дальнейшего развития** через:  
1) увеличение датасета;  
2) более глубокий анализ всего текста в каждой книге, а не только его частей;  
3) исправление технических погрешностей (в случаях, если библиографии, примечания и пр. отсутствуют).
:::
